In [21]:
import pandas as pd

In [22]:
df1 = pd.read_csv('china02.csv')
df1
#print(df1.shape)
#df1.head()

,년월,이용자 구분,시도명,읍면동명,업종,방문인구,이용자수,이용금액,데이터기준일자
0,18-Jan,중국인관광객,서귀포시,남원읍,쇼핑,179846.027,744,4.836000e+06,2020-12-15
1,18-Jan,중국인관광객,제주시,연동,문화/레져,632381.932,744,3.943200e+06,2020-12-15
2,18-Jan,중국인관광객,제주시,연동,소매,632381.932,2240928,5.050000e+11,2020-12-15
3,18-Jan,중국인관광객,제주시,연동,쇼핑,632381.932,5039112,4.770000e+12,2020-12-15
4,18-Jan,중국인관광객,제주시,연동,숙박,632381.932,178560,3.124794e+10,2020-12-15
...,...,...,...,...,...,...,...,...,...
2136,18-Dec,중국인관광객,서귀포시,표선면,문화/레져,64744.126,4464,2.663520e+08,2020-12-15
2137,18-Dec,중국인관광객,서귀포시,표선면,소매,64744.126,400272,1.080000e+11,2020-12-15
2138,18-Dec,중국인관광객,서귀포시,표선면,쇼핑,64744.126,5952,1.702198e+08,2020-12-15
2139,18-Dec,중국인관광객,제주시,삼도1동,소매,18223.999,3720,6.276384e+08,2020-12-15
2140,18-Dec,중국인관광객,제주시,화북동,쇼핑,6393.284,4431,1.970719e+08,2020-12-15

In [23]:
df1
df1_data=df1.sort_values('업종')
df1_data
c=df1_data[df1_data['업종']=='교통'].index
c_=df1_data.drop(c)
ch=df1_data[df1_data['업종']=='기타'].index
c__=c_.drop(ch)
chi=df1_data[df1_data['업종']=='유흥'].index
c___=c__.drop(chi)
chin=df1_data[df1_data['업종']=='전체'].index
china_=c___.drop(chin)
china_

,년월,이용자 구분,시도명,읍면동명,업종,방문인구,이용자수,이용금액,데이터기준일자
352,18-Mar,중국인관광객,제주시,조천읍,문화/레져,33251.336,11160,2.682120e+08,2020-12-15
1725,18-Oct,중국인관광객,서귀포시,성산읍,문화/레져,168943.139,7440,5.518248e+08,2020-12-15
797,18-May,중국인관광객,제주시,구좌읍,문화/레져,34992.117,3720,4.092000e+07,2020-12-15
775,18-May,중국인관광객,서귀포시,성산읍,문화/레져,78727.451,5952,5.739216e+08,2020-12-15
1792,18-Oct,중국인관광객,서귀포시,표선면,문화/레져,73882.665,7440,6.220584e+08,2020-12-15
...,...,...,...,...,...,...,...,...,...
1568,18-Sep,중국인관광객,서귀포시,표선면,식음료,60319.277,7200,5.428800e+08,2020-12-15
540,18-Apr,중국인관광객,제주시,용담2동,식음료,454017.550,397440,1.640357e+10,2020-12-15
1471,18-Sep,중국인관광객,제주시,일도2동,식음료,27062.255,16560,5.397840e+08,2020-12-15
535,18-Apr,중국인관광객,제주시,이호동,식음료,9455.147,720,1.656000e+07,2020-12-15
1565,18-Sep,중국인관광객,제주시,건입동,식음료,105553.487,275040,1.717649e+10,2020-12-15

In [24]:
china_=china_.drop(['년월','이용자 구분','시도명','읍면동명','방문인구','이용금액','데이터기준일자',axis=1])

SyntaxError: invalid syntax (<ipython-input-24-5fc386fc9924>, line 1)

In [26]:
data=pd.DataFrame(china_['이용자수'].groupby(china_['업종']).sum())
data

            이용자수
업종
문화/레져    7154802
소매      73405397
쇼핑     140271718
숙박      11738850
식음료     43130787

In [27]:
data.to_csv('data1.csv',index=True)